[package]
name = "boolean"
version = "0.1.0"
authors = ["William Goodall <wgoodall01@gmail.com>"]
edition = "2018"

[workspace]
members = ["cli", "www"]

[dependencies]
simple-error = "0.2.1"
itertools = "0.8.2"
